name: Push to Replicate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: arboreal-ci-high-ram
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN_ARBOREAL_AI }}

      - name: Push to Replicate
        run: |
          cog push r8.im/arboreal-ai/cog-nexusraven-v2-13b
